
name: Build Linux AMD64 Binary

on:
  push:
    tags:
      - '*' # 触发条件：推送任何标签

permissions:
  contents: write # 允许创建 GitHub Release

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史以支持 GoReleaser 的 changelog

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable' # 使用最新稳定 Go 版本
          cache: true # 缓存 Go 模块

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # 用于发布 Release
