name: Build Go Binary for Linux AMD64

on:
  push:
    branches: [ main ] # 触发条件：推送到 main 分支
  pull_request:
    branches: [ main ] # 触发条件：对 main 分支的 PR

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行器

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # 检出仓库代码

    - name: Set up Go
      uses: actions/setup-go@v5 # 设置 Go 环境
      with:
        go-version: '1.21' # 指定 Go 版本（根据你的项目需求调整）

    - name: Build for Linux AMD64
      run: |
        GOOS=linux GOARCH=amd64 go build -o myprogram-linux-amd64 main.go
      env:
        CGO_ENABLED: 0 # 禁用 CGO，确保生成静态二进制文件

    - name: Upload artifact
      uses: actions/upload-artifact@v4 # 上传编译后的二进制文件
      with:
        name: myprogram-linux-amd64
        path: myprogram-linux-amd64
