version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    dir: .
    main: ./main.go
    binary: douban
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - configs/*

release:
  github:
    owner: your-username # 替换为你的 GitHub 用户名
    name: your-repo # 替换为你的仓库名

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude: # 修复：改为 exclude
      - '^docs:'
      - '^test:'
