```yaml
name: Build and Release Linux AMD64

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24' # 匹配 go1.24.4
          cache: true
      - name: Debug Go environment
        run: |
          go version
          go env
          ls -la
          cat .goreleaser.yaml # 修复：使用 .yaml
          go list -m all
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 'v2.12.0' # 明确版本
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
